language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.12.7
  
before_script:
  - bower install
  - npm install -g protractor
  - webdriver-manager update
  - node run deploy &
  - sleep 2 # give it some time to start